# Generated by Django 5.2.1 on 2025-06-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
