# Generated by Django 5.2.1 on 2025-06-03 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_pieza_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.pieza')),
            ],
        ),
    ]
