# Generated by Django 5.2.1 on 2025-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='requiere_vencimiento',
            field=models.BooleanField(default=False),
        ),
    ]
