# Generated by Django 5.2.1 on 2025-06-03 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_pieza_requiere_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
