# Generated by Django 5.2.1 on 2025-06-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_lote_fecha_emision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='inventario.pieza')),
            ],
        ),
    ]
