# Generated by Django 5.2.1 on 2025-06-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_categoria_proveedor_ubicacion_pieza_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
