# Generated by Django 5.2.1 on 2025-06-08 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_pieza_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
    ]
