# Generated by Django 5.2.1 on 2025-06-08 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_movimientolote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.kit')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pieza')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='piezas',
            field=models.ManyToManyField(through='inventario.KitItem', to='inventario.pieza'),
        ),
    ]
