# Generated by Django 5.2.1 on 2025-06-01 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin_sistema', 'Administrador del Sistema'), ('gestor_inventario', 'Gestor de Inventario'), ('comprador', 'Comprador'), ('almacen_logistica', 'Almacén/Logística'), ('jefe_produccion', 'Jefe de Producción'), ('auditor_inventario', 'Auditor de Inventario'), ('gerente_proyectos', 'Gerente de Proyectos'), ('usuario_final', 'Usuario Final')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
